### ISSUE TITLE
crash when run rails routes

### ISSUE THREAD

**Issue by alex-marmot** [rubyide/vscode-ruby#105]
### Your environment

- `vscode-ruby` version: 
- Ruby version:  ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
- VS Code version:  1.8.1
- Operating System:  MacOS
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
debugger, breakpoint works all fine. 
But when I run `rails routes`..

### Actual behavior

> /Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'ruby-debug-ide'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `blank?' for class `Debase::XmlPrinter::ExceptionProxy'
Did you mean?  blank?
Backtrace for gem load error is:
/Users/alex/.rvm/gems/ruby-2.3.1/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide/xml_printer.rb:8:in `undef_method'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide/xml_printer.rb:8:in `block in <class:ExceptionProxy>'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide/xml_printer.rb:8:in `each'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide/xml_printer.rb:8:in `<class:ExceptionProxy>'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide/xml_printer.rb:7:in `<class:XmlPrinter>'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide/xml_printer.rb:6:in `<module:Debugger>'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide/xml_printer.rb:4:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide.rb:12:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `require'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `each'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `block in require'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `each'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `require'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler.rb:106:in `require'
/Users/alex/workspace/youka/youka-web/config/application.rb:7:in `<top (required)>'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `each'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `each'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `require'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.1/lib/bundler.rb:106:in `require'
	from /Users/alex/workspace/youka/youka-web/config/application.rb:7:in `<top (required)>'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/alex/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

### Steps to reproduce the problem
1.  add the two gems in Gemfiles
2. here is my config

> {
      "name": "Rails server",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rails",
      "useBundler": true,
	    "pathToBundler": "/Users/alex/.rvm/gems/ruby-2.3.1/bin/bundle",
      "showDebuggerOutput": true,
      "args": [
        "server",
        "-b",
        "0.0.0.0"
      ]
    },
3. then run the rails command

**Comment by alex-marmot** [comment]
Sorry for the silly question..
