### ISSUE TITLE
Ruby Debugger won't install on Windows 10 x64

### ISSUE THREAD

**Issue by AxDSan** [rubyide/vscode-ruby#186]
### Your environment

- `vscode-ruby` version: 0.12.1 - April 25 2017
- Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
- VS Code version: 1.14.2 
- Operating System: Windows 10 Pro (Version: 1607) (x64)
- Hardware (optional): N/A

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

To successfully install `ruby-debug-ide` without any problems.

### Actual behavior

I receive an error when I try to install it (`ruby-debug-ide`) through gem, I can't really understand it, the log is here:

```
D:\DevStuff\Ruby Projects\first rubt shet>gem install ruby-debug-ide -v 0.6.0
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-debug-ide:
        ERROR: Failed to build gem native extension.

    current directory: D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.0/ext
D:/Ruby24-x64/bin/ruby.exe mkrf_conf.rb
Installing base gem
Building native extensions.  This could take a while...
Building native extensions.  This could take a while...
ERROR: Failed to build gem native extension.

    current directory: D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/debase-0.2.2.beta10/ext
D:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170728-15452-1iokldz.rb extconf.rb
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/Ruby24-x64/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from D:/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
        from extconf.rb:31:in `block in <main>'
        from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/debase-ruby_core_source-0.9.9/lib/debase/ruby_core_source.rb:15:in `create_makefile_with_core'
        from extconf.rb:47:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  D:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/debase-0.2.2.beta10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/debase-0.2.2.beta10 for inspection.
Results logged to D:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/debase-0.2.2.beta10/gem_make.out
D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:92:in `run'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
  D:/Ruby24-x64/lib/ruby/2.4.0/tempfile.rb:295:in `open'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/ext_conf_builder.rb:31:in `build'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:164:in `block (2 levels) in build_extension'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:163:in `chdir'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:163:in `block in build_extension'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:162:in `synchronize'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:162:in `build_extension'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `each'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/ext/builder.rb:198:in `build_extensions'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/installer.rb:752:in `build_extensions'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/installer.rb:304:in `install'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/resolver/specification.rb:97:in `install'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/request_set.rb:166:in `block in install'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `each'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/request_set.rb:156:in `install'
  D:/Ruby24-x64/lib/ruby/2.4.0/rubygems/dependency_installer.rb:405:in `install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-debug-ide-0.6.0 for inspection.
Results logged to D:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby-debug-ide-0.6.0/gem_make.out
```

As the error itself says, the output of `mkmf.log` is here:

```
"x86_64-w64-mingw32-gcc -o conftest.exe -ID:/Ruby24-x64/include/ruby-2.4.0/x64-mingw32 -ID:/Ruby24-x64/include/ruby-2.4.0/ruby/backward -ID:/Ruby24-x64/include/ruby-2.4.0 -I. -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -IC:/msys64/mingw64/lib/libffi-3.2.1/include -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -march=x86-64 -mtune=generic -O2 -pipe -IC:/msys64/mingw64/lib/libffi-3.2.1/include conftest.c  -L. -LD:/Ruby24-x64/lib -L. -pipe     -lx64-msvcrt-ruby240  -lgmp -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */


```

### Steps to reproduce the problem

Unknown, or It's not reproducible, the problem relies in my system.

**Comment by rebornix** [comment]
@AxDSan do you mind filing issues to https://github.com/ruby-debug/ruby-debug-ide ?

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by wingrunr21** [comment]
@sam1214 that is not an issue with this extension. That seems to be an issue with your Rubygems installation. A quick Google turns up [this page](https://guides.rubygems.org/ssl-certificate-update/) about SSL certificates.

**Comment by sam1214** [comment]
I am able to install debase when I run this command gem install debase --source http://rubygems.org
