### ISSUE TITLE
No Linting, error in console about lintBuilders[l] is not a constructor

### ISSUE THREAD

**Issue by wesbaker** [rubyide/vscode-ruby#205]
### Your environment

- `vscode-ruby` version: 1.16.0
- Ruby version: 0.15.0
- VS Code version: 1.16.0
- Operating System: macOS 10.12.6
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

When I save, I expect the file to lint.

### Actual behavior

No linting occurs and I see this error in the console:

```
shell.ts:419 [rebornix.Ruby] lintBuilders[l] is not a constructor: TypeError: lintBuilders[l] is not a constructor
	at Linter._runLinters (/Users/wbaker/.vscode/extensions/rebornix.ruby-0.15.0/out/lint/lib/linter.js:102:28)
	at Linter.run (/Users/wbaker/.vscode/extensions/rebornix.ruby-0.15.0/out/lint/lib/linter.js:28:21)
	at LintCollection.run (/Users/wbaker/.vscode/extensions/rebornix.ruby-0.15.0/out/lint/lintCollection.js:21:40)
	at executeLinting (/Users/wbaker/.vscode/extensions/rebornix.ruby-0.15.0/out/ruby.js:107:17)
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at e.$acceptDirtyStateChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:348716)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:423958)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280554)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280244)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:279271
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:281190
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:56058
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:102495)```
```

### Steps to reproduce the problem

1. Install the above versions
2. Open a ruby file, make an obvious mistake a linter would catch
3. Save file

**Comment by wesbaker** [comment]
If I only I could spell `rubocop`...
