### ISSUE TITLE
Incompatibility of ruby-debug-ide versions or other gem

### ISSUE THREAD

**Issue by t00lmaker** [rubyide/vscode-ruby#219]
- `vscode-ruby` version: 0.15.0
- Ruby version: 2.3.4
- VS Code version: 1.17.2 
- Operating System: OSX

I installed the plugin as directed here [plugin page](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby), however when trying to debug a rails application, I come across the following problem:

> /Users/toolmaker/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/specification.rb:2159:in** `method_missing': undefined method `this' for #<Gem::Specification:0x3fe55d80b308 ruby-debug-ide-0.6.0> (NoMethodError)
> 	from /Users/toolmaker/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
> 	from /Users/toolmaker/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
> 	from /Users/toolmaker/.rvm/gems/ruby-2.3.4/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:12:in `<top (required)>'
> 	from /Users/toolmaker/.rvm/gems/ruby-2.3.4/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:8:in `require_relative'
> 	from /Users/toolmaker/.rvm/gems/ruby-2.3.4/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:8:in `<top (required)>'
> 	from /Users/toolmaker/.rvm/gems/ruby-2.3.4/bin/rdebug-ide:22:in `load'
> 	from /Users/toolmaker/.rvm/gems/ruby-2.3.4/bin/rdebug-ide:22:in `<main>'
> 	from /Users/toolmaker/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
> 	from /Users/toolmaker/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'

As you can see I'm using rvm, and I've tried to install the latest versions of gems ruby-debug-ide and debase.

**Comment by t00lmaker** [comment]
I just solved the issue by updating rubygems to version: 

> $ gem update --system

`https://stackoverflow.com/questions/43012447/error-running-ruby-debug-ide-with-rails-4-app
`
