### ISSUE TITLE
Vscode debug error

### ISSUE THREAD

**Issue by vimaciel** [rubyide/vscode-ruby#375]
### Your environment

- `vscode-ruby` version: 0.20.0
- Ruby version: 2.3.1p112
- Ruby version manager (if any):
- VS Code version: 1.25.1
- Operating System: elementary OS 0.4.1 Loki 
- Using language server? Yes

### Expected behavior
I have a Ruby on Rails application with Docker. I want to debug my app using the debug menu on vscode. Before that, I run `docker-compose up -d`, which runs my containers detached and then I execute the debugger to run in attach mode.

_My launch.json config_

```json
"version": "0.2.0",
 "configurations": [
        {
            "name": "Rails Remote",
            "type": "Ruby",
            "request": "attach",
            "cwd": "${workspaceRoot}",
            "remoteHost": "localhost",
            "remotePort": "3000",
            "remoteWorkspaceRoot": "${workspaceRoot}"
        }        
 ]
```
_Gems installed_

- bigdecimal (1.2.8)
- debase (0.2.3.beta2, 0.2.2)
- debase-ruby_core_source (0.10.3)
- did_you_mean (1.0.0)
- domain_name (0.5.20180417)
- http-cookie (1.0.3)
- io-console (0.4.5)
- json (1.8.3)
- mime-types (3.1)
- mime-types-data (3.2016.0521)
- mini_portile2 (2.1.0)
- minitest (5.8.4)
- net-telnet (0.1.1)
- netrc (0.11.0)
- nokogiri (1.6.8)
- pkg-config (1.1.9)
- power_assert (0.2.7)
- psych (2.0.17)
- rake (12.3.1, 10.5.0)
- rdoc (4.2.1)
- rest-client (2.0.2)
- ruby-debug-ide (0.7.0.beta6, 0.6.1)
- test-unit (3.1.7)
- unf (0.1.4)
- unf_ext (0.0.7.5)

### Actual behavior

Executing with Start Debugging button on vscode at debug section reproduces the following error:

> `TypeError: Cannot read property 'Run' of undefined
    at RubyDebugSession.configurationDoneRequest (/home/vinicius/.vscode/extensions/rebornix.ruby-0.20.0/out/debugger/main.js:113:25)
    at RubyDebugSession.dispatchRequest (/home/vinicius/.vscode/extensions/rebornix.ruby-0.20.0/node_modules/vscode-debugadapter/lib/debugSession.js:362:22)
    at RubyDebugSession._handleData (/home/vinicius/.vscode/extensions/rebornix.ruby-0.20.0/node_modules/vscode-debugadapter/lib/protocol.js:97:38)
    at Socket.inStream.on (/home/vinicius/.vscode/extensions/rebornix.ruby-0.20.0/node_modules/vscode-debugadapter/lib/protocol.js:18:44)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)`

**Comment by such** [comment]
@vimaciel I have the same error. Have you been able to make progress?

**Comment by vimaciel** [comment]
@such No, I haven't. Have you had any progress since your last question?

**Comment by vimaciel** [comment]
No, I haven't. Have you had any progress since your last question?

**Comment by vimaciel** [comment]
No, I haven't. Have you had any progress since your last question?

**Comment by vimaciel** [comment]
@such No, I haven't. Have you had any progress since your last question?

**Comment by andrewmcodes** [comment]
Try this setup. 
```
{
  "name": "Rails server",
  "type": "Ruby",
  "request": "launch",
  "cwd": "${workspaceRoot}",
  "program": "${workspaceRoot}/bin/rails",
  "args": [
     "server"
  ]
}
```

Though since you’re running in a docker container, I feel like there will be issues using the debugger, that won’t be easy (if even possible) to fix.

**Comment by andrewmcodes** [comment]
Also check out issue#356
