### ISSUE TITLE
rubocop issue

### ISSUE THREAD

**Issue by Osiecki** [rubyide/vscode-ruby#383]
I have an issue when running rake.

Running RuboCop...
cannot load such file -- rubocop-rspec
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader_resolver.rb:15:in `require'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader_resolver.rb:11:in `each'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader.rb:43:in `load_file'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader.rb:82:in `configuration_from_file'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_store.rb:44:in `for'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:152:in `ruby_interpreters'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:145:in `ruby_executable?'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:161:in `ruby_file?'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:76:in `to_inspect?'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:65:in `block in target_files_in_dir'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:64:in `select'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:64:in `target_files_in_dir'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:31:in `find'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/runner.rb:58:in `find_target_files'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/runner.rb:34:in `run'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/cli.rb:160:in `execute_runner'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/cli.rb:88:in `execute_runners'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/cli.rb:41:in `run'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/rake_task.rb:44:in `run_cli'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/rake_task.rb:28:in `block (2 levels) in initialize'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/file_utils_ext.rb:59:in `verbose'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/rake_task.rb:26:in `block in initialize'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:271:in `call'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/schrods/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/Users/schrods/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/Users/schrods/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/Users/schrods/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/bin/rake:23:in `load'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/bin/rake:23:in `<main>'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/bin/ruby_executable_hooks:24:in `eval'
/Users/schrods/.rvm/gems/ruby-2.1.9@puppet/bin/ruby_executable_hooks:24:in `<main>'
RuboCop failed!

I was originally using my system ruby, but tried to install rvm, and am still having the issue.
I've tried uninstalling and reinstalling  several versions of RuboCop.
0.57.2
0.51.0, and
0.53.0

by doing
vi Gemfile from
  gem 'rubocop', '~> 0.57.2',                                      :require => false

rm -rf Gemfile.lock
rvm gemset empty
bundle install
and then retrying rake.

Besides the number of offenses, which we can ignore from version to version, I'm having a common set of files it's having issues with.
config_loader_resolver.rb config_loader.rb config_store.rb result_cache.rb runner.rb cli.rb rake_task.rb

Can you guys help, please?
I'm running
macOS High Sierra 10.13.6
ruby --version
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-darwin17.0]
rvm gemset list

gemsets for ruby-2.1.9 (found in /Users/schrods/.rvm/gems/ruby-2.1.9)
   (default)
   global
=> puppet

I also did a fresh fetch of our team's project from git, and those files are still different for me from my group's

whereis ruby
/usr/bin/ruby

gem --version
2.7.7

I'm missing something. Can I request help, please?

**Comment by Osiecki** [comment]
I was able to replicate the issue.
With a fresh git clone, run bundle install, and rake works
librarian-puppet install, after running sudo xcodebuild -license, recreated the error.

rake
Running RuboCop...
Inspecting 4 files
....

4 files inspected, no offenses detected
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml

All tests passing...
s-MBPR:puppet s$ bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Using rake 12.3.1
Using CFPropertyList 2.2.8
Using public_suffix 3.0.3
Using addressable 2.5.2
Using ast 2.4.0
Using bundler 1.16.2
Using diff-lcs 1.3
Using facter 2.5.1 (universal-darwin)
Using jgrep 1.5.0
Using facterdb 0.5.2
Using multipart-post 2.0.0
Using faraday 0.13.1
Using faraday_middleware 0.12.2
Using fast_gettext 1.1.2
Using locale 2.1.2
Using text 1.3.1
Using gettext 3.2.9
Using gettext-setup 0.30
Using hiera 3.4.4
Using jaro_winkler 1.5.1 (x86_64-darwin-17)
Using json 2.1.0
Using json-schema 2.8.0
Using json_pure 1.8.6
Using thor 0.20.0
Using librarianp 0.6.4
Using minitar 0.6.1
Using semantic_puppet 1.0.2
Using puppet_forge 2.2.9
Using rsync 1.0.9
Fetching librarian-puppet 3.0.0
Installing librarian-puppet 3.0.0
Using stomp 1.4.4
Using systemu 2.6.5
Using mcollective-client 2.12.3
Using metaclass 0.0.4
Using spdx-licenses 1.2.0
Using metadata-json-lint 2.2.0
Using mini_portile2 2.1.0
Using mocha 1.7.0
Using nokogiri 1.7.2
Using parallel 1.12.1
Using parser 2.5.1.2
Using powerpack 0.1.2
Using puppet 4.10.12 (universal-darwin)
Using puppet-lint 2.3.6
Using puppet-lint-absolute_classname-check 0.2.5
Using puppet-lint-absolute_template_path 1.0.1
Using puppet-lint-alias-check 0.1.1
Using puppet-lint-classes_and_types_beginning_with_digits-check 0.1.2
Using puppet-lint-duplicate_class_parameters-check 1.0.4
Using puppet-lint-empty_string-check 0.2.2
Using puppet-lint-extended 1.0.1
Using puppet-lint-file_ensure-check 0.3.1
Using puppet-lint-file_source_rights-check 0.1.1
Using puppet-lint-leading_zero-check 0.1.1
Using puppet-lint-numericvariable 1.0.3
Using puppet-lint-resource_reference_syntax 1.0.14
Using puppet-lint-roles_and_profiles-check 0.1.1
Using puppet-lint-security-plugins 0.2.0
Using puppet-lint-spaceship_operator_without_tag-check 0.1.1
Using puppet-lint-strict_indent-check 2.0.5
Using puppet-lint-trailing_comma-check 0.3.2
Using puppet-lint-trailing_newline-check 1.1.0
Using puppet-lint-undef_in_function-check 0.2.1
Using puppet-lint-unquoted_string-check 0.3.0
Using puppet-lint-variable_contains_upcase 1.2.0
Using puppet-lint-version_comparison-check 0.2.1
Using puppet-syntax 2.4.1
Using rspec-support 3.8.0
Using rspec-core 3.8.0
Using rspec-expectations 3.8.1
Using rspec-mocks 3.8.0
Using rspec 3.8.0
Using rspec-puppet 2.6.15
Using puppetlabs_spec_helper 2.10.0
Using rainbow 3.0.0
Using rspec-puppet-facts 1.9.0
Using ruby-progressbar 1.10.0
Using unicode-display_width 1.4.0
Using rubocop 0.57.2
Bundle complete! 31 Gemfile dependencies, 79 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
s-MBPR:puppet s$ rake
Running RuboCop...
Inspecting 4 files
....

4 files inspected, no offenses detected
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml

All tests passing...
s-MBPR:puppet s$ librarian-puppet install
s-MBPR:puppet s$ rake
Running RuboCop...
cannot load such file -- rubocop-rspec
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader_resolver.rb:15:in `require'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader_resolver.rb:11:in `each'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader.rb:43:in `load_file'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_loader.rb:82:in `configuration_from_file'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/config_store.rb:44:in `for'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:152:in `ruby_interpreters'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:145:in `ruby_executable?'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:161:in `ruby_file?'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:76:in `to_inspect?'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:65:in `block in target_files_in_dir'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:64:in `select'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:64:in `target_files_in_dir'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/target_finder.rb:31:in `find'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/runner.rb:58:in `find_target_files'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/runner.rb:34:in `run'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/cli.rb:160:in `execute_runner'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/cli.rb:88:in `execute_runners'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/cli.rb:41:in `run'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/rake_task.rb:44:in `run_cli'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/rake_task.rb:28:in `block (2 levels) in initialize'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/file_utils_ext.rb:59:in `verbose'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rubocop-0.57.2/lib/rubocop/rake_task.rb:26:in `block in initialize'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:271:in `call'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/s/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/Users/s/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/Users/s/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/Users/s/.rvm/rubies/ruby-2.1.9/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/bin/rake:23:in `load'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/bin/rake:23:in `<main>'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/bin/ruby_executable_hooks:24:in `eval'
/Users/s/.rvm/gems/ruby-2.1.9@puppet/bin/ruby_executable_hooks:24:in `<main>'
RuboCop failed!

**Comment by Osiecki** [comment]
Fix: remove the .librarian/puppet/config file's contents, rerun bundle install and librarian-puppet install, and rake works.
