### ISSUE TITLE
Ruby minitest and rake (no rails)

### ISSUE THREAD

**Issue by pitosalas** [rubyide/vscode-ruby#396]
vscode 1.28.1, ruby extension 0.20.0

My directory structure looks like this:
.
├── Gemfile
├── Gemfile.lock
├── Rakefile
├── Readme.md
├── bin
│   ├── bundle
│   ├── byebug
│   ├── coderay
│   ├── gdb_wrapper
│   ├── ha
│   ├── pry
│   ├── rake
│   ├── rdebug-ide
│   └── thor
├── ha.gemspec
├── lib
│   ├── ha
│   │   ├── context.rb
│   │   ├── group.rb
│   │   ├── hue.rb
│   │   ├── hue_command.rb
│   │   ├── light.rb
│   │   ├── sensor.rb
│   │   └── version.rb
│   └── ha.rb
├── play.text
└── test
    ├── ha_test.rb
    ├── hue_test.rb
    └── test_helper.rb

[launch.json:]
"version": "0.2.0",
  "configurations": [
    {
      "name": "Rake",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/rake",
    },

`$ rake test` works correctly.

But when I run the debugger with the above configuration I get:

```
Uncaught exception: cannot load such file -- /Users/pitosalas/mydev/ha/rake
	/Users/pitosalas/.rbenv/versions/2.5.0/bin/rdebug-ide:23:in `load'
	/Users/pitosalas/.rbenv/versions/2.5.0/bin/rdebug-ide:23:in `<main>'
/Users/pitosalas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:92:in `debug_load': cannot load such file -- /Users/pitosalas/mydev/ha/rake (LoadError)
	from /Users/pitosalas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:92:in `debug_program'
	from /Users/pitosalas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ruby-debug-ide-0.6.1/bin/rdebug-ide:182:in `<top (required)>'
	from /Users/pitosalas/.rbenv/versions/2.5.0/bin/rdebug-ide:23:in `load'
	from /Users/pitosalas/.rbenv/versions/2.5.0/bin/rdebug-ide:23:in `<main>'

```
Which is weird because I don't know why it is looking for ./ha/rake.

Any tips? Thanks

**Comment by wingrunr21** [comment]
Looks like `program` is pointing to `rake` that doesn't exist? Does this change fix things?

`"program": "${workspaceRoot}/bin/rake"`

**Comment by wingrunr21** [comment]
Closing due to inactivity

**Comment by sekmo** [comment]
Did you manage to fix it?
