### ISSUE TITLE
Language server fails sometimes

### ISSUE THREAD

**Issue by rxx** [rubyide/vscode-ruby#402]
### Your environment

- `vscode-ruby` version: 0.20.0
- Ruby version: 2.3.4
- Ruby version manager (if any): rbenv 1.1.1-30-gc8ba27f
- VS Code version: 1.28.2
- Operating System: Fedora
- Using language server? yes

### Expected behavior
Language server works without errors

### Actual behavior

Language server fails on Rails migration files with next error

```
[Error - 11:54:31 AM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'rootNode' of undefined
  Code: -32603 
```
But after restart vscode everything looks fine. When it failes it always show output panel and it's so disgusting

**Comment by rxx** [comment]
@wingrunr21 as I understood, it fails usually when I come back from suspend on my laptop. It crashes on first ruby file and all next files.
When I restart editor, everything is fine

**Comment by connorshea** [comment]
I'm having this same problem, I _think_ I can reproduce it?

https://gist.github.com/connorshea/ca8fdc9bdd596d8a8be73ca0b6b74a73

```
[Info  - 7:56:50 PM] Initializing Ruby language server...
[Info  - 7:56:50 PM] Rebuilding tree-sitter for local Electron version
[Info  - 7:56:50 PM] Rebuild succeeded!
TypeError: Cannot read property 'children' of undefined
    at Function.build (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/util/RubyDocumentSymbol.js:48:54)
    at DocumentSymbolAnalyzer.analyze (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/analyzers/DocumentSymbolAnalyzer.js:26:53)
    at Analyzer.analyzeNode (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/Analyzer.js:39:37)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/Analyzer.js:26:18)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/Analyzer.js:29:21)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/Analyzer.js:29:21)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/Analyzer.js:29:21)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/Analyzer.js:29:21)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/Analyzer.js:29:21)
    at Analyzer.analyze (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.23.0/server/out/Analyzer.js:34:9)
[Error - 7:57:49 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 7:57:51 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 7:58:02 PM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'rootNode' of undefined
  Code: -32603 
[Error - 7:58:02 PM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'rootNode' of undefined
  Code: -32603 
[Error - 7:58:03 PM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'rootNode' of undefined
  Code: -32603 
```

**Comment by connorshea** [comment]
I tried creating a minimal version of that file but unfortunately you have to reload the window every time you make a change or it'll just keep throwing these errors regardless of the file's contents.

**Comment by connorshea** [comment]
Actually, I just noticed something _really_ interesting.

![image](https://user-images.githubusercontent.com/2977353/60378468-27257100-99e0-11e9-9f74-815497f2204c.png)

Note the `undefined` in the line number gutter...

**Comment by connorshea** [comment]
Okay, I've minimized this from 18000 lines to 13, hopefully that's good enough :)

When I load this file, I get the following errors:

```
[Info  - 9:12:43 PM] Initializing Ruby language server...
[Info  - 9:12:43 PM] Rebuilding tree-sitter for local Electron version
[Info  - 9:12:43 PM] Rebuild succeeded!
TypeError: Cannot read property 'children' of undefined
    at Function.build (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/util/RubyDocumentSymbol.js:48:54)
    at DocumentSymbolAnalyzer.analyze (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/analyzers/DocumentSymbolAnalyzer.js:26:53)
    at Analyzer.analyzeNode (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/Analyzer.js:39:37)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/Analyzer.js:26:18)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/Analyzer.js:29:21)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/Analyzer.js:29:21)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/Analyzer.js:29:21)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/Analyzer.js:29:21)
    at walk (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/Analyzer.js:29:21)
    at Analyzer.analyze (/Users/connorshea/.vscode/extensions/rebornix.ruby-0.24.0/server/out/Analyzer.js:34:9)
[Error - 9:12:44 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 9:12:44 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
```

File:

```ruby
module Bundler
  class Thor
    def self.package_name(name, _ = {}); end

    module Base
      def options(); end

      module ClassMethods
        def attr_reader(); end
      end
    end
  end
end
```

**Comment by connorshea** [comment]
Even more minimal:

```ruby
module Bundler
  class Thor
    module Base
      module ClassMethods
        def attr_reader(); end
      end
    end
  end
end
```

**Comment by yagudaev** [comment]
I keep seeing this error today over and over and over again.

It is quite annoying as I'm trying to use the integrated terminal and this error keeps popping up.

**Comment by klueless-io** [comment]
I'm having this issue too

**Comment by wingrunr21** [comment]
@klueless-io RuboCop is erroring on the `-R` flag. It doesn't appear the language server is crashing, it's just printing out the error. If you disable RuboCop or fix the `-R` support it should go away

**Comment by Overload119** [comment]
This issue keeps popping up my VS Code output to spit this message out:

```
[Error - 9:06:22 AM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'rootNode' of undefined
  Code: -32603 
[Error - 9:32:28 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
```

How can I at least disable it from doing this?
