### ISSUE TITLE
Plugin load failure

### ISSUE THREAD

**Issue by klauern** [rubyide/vscode-ruby#430]
### Your environment

- `vscode-ruby` version: `0.21.1`
- Ruby version: `rbenv` usage
- Ruby version manager (if any): `rbenv`
- VS Code version: 1.31.1
- Operating System: MacOS
- Using language server? ????

### Expected behavior

Plugin load failure (from the Extension Host Logs)

## Extension Host Logs

```
[2019-02-18 10:24:39.233] [renderer1] [error] Cannot read property 'then' of undefined: TypeError: Cannot read property 'then' of undefined
    at Locate.listInFile (/Users/nklauer/.vscode/extensions/rebornix.ruby-0.21.1/out/locate/locate.js:69:29)
    at Object.provideDocumentSymbols (/Users/nklauer/.vscode/extensions/rebornix.ruby-0.21.1/out/providers/intellisense.js:48:31)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:536:745
    at t.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:385)
    at new Promise (<anonymous>)
    at Object.t.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:353)
    at e.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:536:705)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:554:222
    at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:553:292)
    at e.$provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:554:184)
    at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644:118)
    at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643:744)
    at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:256)
    at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:155)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:960
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38:994
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:113)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:213)
    at Socket.f._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:434)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by wingrunr21** [comment]
This appears to be a problem with rubyLocate. What are your settings for that?

Also, are you using the language server?

**Comment by klauern** [comment]
I don't know how to find that.  I was trying to use the language server, but with all of our projects running on `rbenv`, I'm not sure how that works.

**Comment by wingrunr21** [comment]
It should all be in your VSCode settings. I'm not going to be able to help very much without some more information.

**Comment by klauern** [comment]
Yes, I'm using the language server:

![image](https://user-images.githubusercontent.com/4735/52977272-4b1dd980-3392-11e9-9941-9423cdaa1c5c.png)

```json
  "ruby.codeCompletion": "rcodetools",
  "ruby.useBundler": true,
  "ruby.format": "rubocop",
  "ruby.intellisense": "rubyLocate",
  "ruby.useLanguageServer": true,
```

**Comment by wingrunr21** [comment]
And what about `rubyLocate`? Is it in your bundle or globally installed? How are you starting VSCode (eg are you opening from the command line? what command are you using and from what directory?)?

**Comment by klauern** [comment]
I don't have `rubyLocate`.  To run VSCode, i use the `code` shim within a directory to open the workspace folder at that point. The directory is my `/Users/nklauer/dev/<project location>`.

**Comment by klauern** [comment]
All of the options that I just pasted are the only ones set on the User profile, and I have no Workspace settings.

**Comment by wingrunr21** [comment]
Ah, sorry, forgot `rubyLocate` is an npm module.

Does this happen independent of the directory you start VSCode within? It appears to be bombing out on [this line](https://github.com/rubyide/vscode-ruby/blob/master/src/locate/locate.js#L74)

**Comment by klauern** [comment]
I tried a completely different project using the same startup (`code .` from the directory of the project) and the same error crops up.

**Comment by wingrunr21** [comment]
I'll need to look into this deeper. Without exact reproduction steps it may take awhile though. It could also be just a part of the legacy functionality not working consistently. That aspect is scheduled to be replaced at some point so that may end up being the direction I take here.

**Comment by connorshea** [comment]
I think the 'then' issue was resolved?
