### ISSUE TITLE
Language Server failure when opening single file

### ISSUE THREAD

**Issue by TeeSeal** [rubyide/vscode-ruby#431]
### Your environment

- `vscode-ruby` version: 0.22.0
- Ruby version: 2.4.2
- Ruby version manager (if any): rbenv
- VS Code version: 1.31.1
- Operating System: macOS
- Using language server? trying to

### Expected behavior
No crash.

### Actual behavior
The language server crashes when opening single file instead of a directory.
i.e
```shell
$ code . # doesn't crash
$ code main.rb # crashes
```

Console output:
```
/Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; });
                             ^

TypeError: Cannot read property 'uri' of undefined
    at SettingsCache.<anonymous> (/Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/out/SettingsCache.js:34:70)
    at Generator.next (<anonymous>)
    at /Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/out/SettingsCache.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/out/SettingsCache.js:3:12)
    at SettingsCache.get (/Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/out/SettingsCache.js:33:16)
    at rxjs_1.from.pipe.operators_1.mergeMap.config (/Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/out/Linter.js:27:164)
    at MergeMapSubscriber.project (/Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/node_modules/rxjs/internal/operators/mergeMap.js:24:101)
    at MergeMapSubscriber._tryNext (/Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/teeseal/.vscode/extensions/rebornix.ruby-0.22.0/server/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
[Error - 4:50:14 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by wingrunr21** [comment]
Can you post your settings?

**Comment by TeeSeal** [comment]
Sure. No worries, I don't actually "need" this to work. Just stumbled upon it accidentally and thought I'd report.

**Comment by wingrunr21** [comment]
Cool. I appreciate the report!
