### ISSUE TITLE
Language server fails on the startup due to Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by deepj** [rubyide/vscode-ruby#454]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: Ruby 2.5.3
- Ruby version manager (if any): chruby
- VS Code version: 1.32.2
- Operating System: macOS
- Using language server?

### Expected behavior
It will start up

### Actual behavior

I get the following issue

```
[Info  - 10:31:59 AM] Initializing Ruby language server...
[Info  - 10:31:59 AM] Rebuilding tree-sitter for local Electron version
[Info  - 10:32:00 AM] Rebuild succeeded!
TypeError: Cannot read property 'children' of undefined
    at Function.build (~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/util/RubyDocumentSymbol.js:48:54)
    at DocumentSymbolAnalyzer.analyze (~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/analyzers/DocumentSymbolAnalyzer.js:26:53)
    at Analyzer.analyzeNode (~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/Analyzer.js:39:37)
    at walk (~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/Analyzer.js:26:18)
    at walk (~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/Analyzer.js:29:21)
    at walk (~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/Analyzer.js:29:21)
    at Analyzer.analyze (~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/Analyzer.js:34:9)
    at MapSubscriber.Forest_1.forestStream.pipe.operators_1.map [as project] (~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/Analyzer.js:68:25)
    at MapSubscriber._next (~/.vscode/extensions/rebornix.ruby-0.22.3/server/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (~/.vscode/extensions/rebornix.ruby-0.22.3/server/node_modules/rxjs/internal/Subscriber.js:66:18)
[Error - 6:49:02 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 6:49:02 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 6:49:05 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 6:49:05 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 6:49:10 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 6:49:11 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 6:49:12 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 6:49:12 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 6:49:13 PM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'rootNode' of undefined
  Code: -32603 
[Error - 6:49:14 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 6:49:14 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 6:49:15 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 6:49:15 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 6:49:16 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 6:49:16 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 6:49:17 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 6:49:17 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
```
Please, ignore `~` in paths. It's "obfuscation" for publishing this issue.

**Comment by wingrunr21** [comment]
Does this happen for all Ruby files (even simple ones like `puts 'foo'`)?

**Comment by deepj** [comment]
@wingrunr21 Hello, sorry for delay. But I've never seen this again since that. I guess, this can be closed since that I met this again.

**Comment by wingrunr21** [comment]
ok, great thanks! Please open a new issue if you see this again!

**Comment by solnic** [comment]
This is still an issue, I think it happens when the underlying formatter crashes

**Comment by wingrunr21** [comment]
Do you have a consistent way of reproducing?

**Comment by solnic** [comment]
@wingrunr21 yes - for example it chokes like that on [this file](https://github.com/rom-rb/rom/blob/master/core/lib/rom/relation.rb)

**Comment by wingrunr21** [comment]
Great thanks

**Comment by connorshea** [comment]
I created a more minimal reproduction case of this issue in #402:

```ruby
module Bundler
  class Thor
    module Base
      module ClassMethods
        def attr_reader(); end
      end
    end
  end
end
```

**Comment by connorshea** [comment]
This definitely has something to do with the `attr_*` handling code: https://github.com/rubyide/vscode-ruby/blob/master/server/src/util/RubyDocumentSymbol.ts#L48-L66

This doesn't fail, for example:

```ruby
module Bundler
  class Thor
    module Base
      module ClassMethods
        def test(); end
      end
    end
  end
end
```

This does:

```ruby
module ROM
  class Relation
    def attr_ast
      schema.map { |t| t.to_read_ast }
    end
  end
end
```

**Comment by connorshea** [comment]
This does not fail, I think because `puts 'test'` is recognized in the Outline:

```ruby
module ROM
  class Relation
    def attr_ast(test, test)
      puts 'test'
    end
  end
end
```

So I think it just needs to add a check to make sure `argumentList` isn't `undefined`?

**Comment by solnic** [comment]
could this be fixed please? how can I help?

**Comment by fxn** [comment]
This is happening to me opening even an empty file with extension ".rb":

```
[Info  - 3:55:10 PM] Initializing Ruby language server...
[Info  - 3:55:10 PM] Rebuilding tree-sitter for local Electron version
[Info  - 3:55:10 PM] Rebuild succeeded!
TypeError: Cannot read property 'children' of undefined
    at Function.build (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/out/util/RubyDocumentSymbol.js:48:54)
    at DocumentSymbolAnalyzer.analyze (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/out/analyzers/DocumentSymbolAnalyzer.js:26:53)
    at Analyzer.analyzeNode (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/out/Analyzer.js:39:37)
    at walk (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/out/Analyzer.js:26:18)
    at walk (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/out/Analyzer.js:29:21)
    at Analyzer.analyze (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/out/Analyzer.js:34:9)
    at MapSubscriber.Forest_1.forestStream.pipe.operators_1.map [as project] (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/out/Analyzer.js:68:25)
    at MapSubscriber._next (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/Users/fxn/.vscode/extensions/rebornix.ruby-0.24.2/server/node_modules/rxjs/internal/operators/switchMap.js:86:26)
```

About Visual Studio Code yields:

```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by wingrunr21** [comment]
Can you upgrade to the current version of the extension?

**Comment by fxn** [comment]
Interesting, `@outdated` didn't show extensions to be upgraded, but going to the page of the extension showed there is a new version.

**Comment by fxn** [comment]
Mistery solved: `Auto Check Updates` was disabled.

Working now, thanks!

**Comment by technicalpickles** [comment]
I've been seeing this on more recent versions, rebornix.ruby-0.28.1 according to the stacktrace.

```
Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```
