### ISSUE TITLE
`Request textDocument/documentSymbol failed` error when closing ruby file tab.

### ISSUE THREAD

**Issue by viktor-evdokimov** [rubyide/vscode-ruby#465]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin17]
- Ruby version manager (if any): rbenv
- VS Code version: Version 1.33.0-insider (1.33.0-insider) 0ac111466ec925fd5ca180ab9893f51531e419b2 2019-04-01T15:39:08.133Z
- Operating System: OS X MOJAVE 10.14 (18A391)
- Using language server? Ruby Solargraph 0.19.3 / Gem version 0.31.3

### Expected behavior
No exception

### Actual behavior
Every time tab with file that has language mode = ruby (no matter extension) is closed, this error appears in the `Ruby Language Server` output:
``` 
[Error - 11:34:07 AM] Request textDocument/documentSymbol failed.
  Message: [ArgumentError] wrong number of arguments (given 4, expected 0)
  Code: -32603 
```
These errors appear in the `Log(window)` output ( redacted home dir to `~`. first error also appear in the `Log(Extension Host)`):
```
[2019-04-02 11:29:51.688] [renderer1] [error] Cannot read property 'then' of undefined: TypeError: Cannot read property 'then' of undefined
	at Locate.listInFile (~/.vscode-insiders/extensions/rebornix.ruby-0.22.3/out/locate/locate.js:69:29)
	at Object.provideDocumentSymbols (~/.vscode-insiders/extensions/rebornix.ruby-0.22.3/out/providers/intellisense.js:55:31)
	at define.provideDocumentSymbols.a.asPromise (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:583:398)
	at t.asPromise.Promise (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:430)
	at new Promise (<anonymous>)
	at Object.t.asPromise (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:49:402)
	at _.provideDocumentSymbols (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:583:369)
	at define.$provideDocumentSymbols._withAdapter.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:599:921)
	at B._withAdapter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:599:159)
	at B.$provideDocumentSymbols (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:599:899)
	at d._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622:11)
	at d._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:716)
	at d._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:341)
	at d._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617:400)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40:460)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at a (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:467)
	at e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:513)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at y._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:415)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at f.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174:410)
	at Socket.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)

[2019-04-02 11:40:39.816] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)


```

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*

**Comment by wingrunr21** [comment]
Are you using the internal language server? Solargraph is not this extension

**Comment by viktor-evdokimov** [comment]
How do I check what language server I am using ?

**Comment by wingrunr21** [comment]
Yes, but I need to know if you are using the internal language server. Do you have the setting `Use Language Server` turned on?

**Comment by viktor-evdokimov** [comment]
So it was off. 
When I turned it on, same error message shows up when I hover any class name in any ruby file *with CMD button pressed.

**Comment by wingrunr21** [comment]
Can you post your configuration? The language server does provide document symbols but given it was turned off something else is doing that.

**Comment by viktor-evdokimov** [comment]
@wingrunr21 

```
    "ruby.lint": {
        "rubocop": true
    },
    "solargraph.diagnostics": true,
    "solargraph.hover":false,
    "ruby.format": "rubocop",
    "ruby.intellisense": "rubyLocate",
    "ruby.useLanguageServer": true,
```

**Comment by connorshea** [comment]
Read property 'then' was resolved by #499 I think?

**Comment by qortex** [comment]
Running into the same error each time I open up `config.ru` file:
```
[Error - 14:39:53] Request textDocument/documentSymbol failed.
  Message: [NoMethodError] undefined method `missing_extensions?' for nil:NilClass
  Code: -32603 
```

Just appeared recently though, so might be linked to a solargraph update. How can I check what part is responsible for the error message? I appears under the "Ruby Language Server" pane, relevant parts of my config:
```
    "ruby.useLanguageServer": true,
    "ruby.format": "rubocop",
    "ruby.lintDebounceTime": 50,
    "ruby.useBundler": true,
    "[ruby]": {
      "editor.defaultFormatter": "misogi.ruby-rubocop"
    },
```

**Comment by qortex** [comment]
It actually happens a **lot** throughout different actions, like when typing `require '...'`, switching files sometimes, just writing random codes... Seems to be related to intellisense somehow.

Anybody encountering that too?

**Comment by qortex** [comment]
Also happens when opening a `Gemfile`.

**Comment by qortex** [comment]
Looks like cleaning cache & stuff made this disappear. Must have been a temporary glitch.

**Comment by TylerSustare** [comment]
I fixed this in my setup by disabling the built-in language server. 

![image](https://user-images.githubusercontent.com/10850753/103804381-e069fb80-5006-11eb-8886-e1cb14231ddf.png)

**Comment by borisbokan** [comment]
Had the same problem for two hours..the solution was that I deleted the variable "final args" .... don't use the reserved words in your code "args is not blocked by the compiler !!" if you use it you will have this kind of problem.
