### ISSUE TITLE
Rspec can not execute 'it'

### ISSUE THREAD

**Issue by clxy** [rubyide/vscode-ruby#52]
### Your environment

- `vscode-ruby` version: 0.5.3
- Ruby version: ruby 2.1.3p242 (2014-09-19 revision 47630) [i386-mingw32]
- VS Code version: 1.4.0
- Operating System: Windows 7 Professional
- rspec (3.5.0)
- ruby-debug-ide (0.6.1.beta2, 0.6.0, 0.5.0, 0.4.32)
- debase (0.2.1)
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
execute rspec test

### Actual behavior
executed everythiing except 'it'

### Steps to reproduce the problem
 rspec test code :

```
describe 'Utils' do

  puts 1111
  describe '#time_condition' do
    puts 2221
    it do
      puts 'aaa'
    end
    puts 2223
  end
end
```

launch.json :
```
...
    {
      "name": "RSpec - all",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/spec/*_rspec.rb",
      "args": [
        "--require",
        "spec_helper",
        "--require",
        "rails_helper",
        "--format",
        "documentation"
      ]
    },
...
```
When I run test on vscode, got
```
1111
2221
2223
```
when I run test by command, got
```
>rspec spec --pattern *_rspec.rb
1111
2221
2223
aaa
.

Finished in 0.003 seconds (files took 0.23602 seconds to load)
1 example, 0 failures
```

by the way, spec config files (generated by rspec --init) :
```
.rspec
--color
--require spec_helper
```

```
spec\spec_helper.rb
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.profile_examples = 10

  config.order = :random

  Kernel.srand config.seed
end
```

**Comment by HookyQR** [comment]
Hey @clxy. Do you have any break points or watches set? I've copied your set up, but can't duplicate the error.

**Comment by clxy** [comment]
No break points or watches.
But I tried add break points before and after 'it' block, Rspec just skiped without any message!

I tried again, This time I stepped into rspec core.
I got error like this:(only when step in)

```
Cannot evaluate self
NoMethodError: undefined method `[]' for nil:NilClass
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example.rb:77:in `description'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example.rb:218:in `inspect'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide/commands/variables.rb:132:in `execute'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide/ide_processor.rb:41:in `block (2 levels) in process_commands'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide/ide_processor.rb:34:in `each'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide/ide_processor.rb:34:in `block in process_commands'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide/ide_processor.rb:33:in `catch'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide/ide_processor.rb:33:in `process_commands'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide/event_processor.rb:58:in `line_event'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide/event_processor.rb:34:in `at_line'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/debase-0.2.1/lib/debase/context.rb:43:in `at_line'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example.rb:187:in `initialize'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:148:in `new'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:148:in `block in define_example_method'
  d:/projects/RubyLib/spec/utils_rspec.rb:47:in `block (2 levels) in <top (required)>'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:385:in `module_exec'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:385:in `subclass'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
  d:/projects/RubyLib/spec/utils_rspec.rb:35:in `block in <top (required)>'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:385:in `module_exec'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:385:in `subclass'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib/rspec/core/dsl.rb:84:in `block (2 levels) in expose_example_group_alias_globally'
  d:/projects/RubyLib/spec/utils_rspec.rb:7:in `<top (required)>'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide.rb:88:in `debug_load'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/lib/ruby-debug-ide.rb:88:in `debug_program'
  D:/Ruby/Ruby21/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.1.beta2/bin/rdebug-ide:130:in `<top (required)>'
  D:/Ruby/Ruby21/bin/rdebug-ide:23:in `load'
  D:/Ruby/Ruby21/bin/rdebug-ide:23:in `<main>'
```

Thank you for answering my question.

**Comment by clxy** [comment]
OK. I solved it!
My fault is setting wrong value to program.
Program must be rspec path.

```
...
    {
      "name": "RSpec - all",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "D:/Ruby/Ruby21/bin/rspec",
      "args": [
        "--pattern",
        "${workspaceRoot}/spec/**/*_rspec.rb"
      ]
    },
...
```
