### ISSUE TITLE
Keeps crashing on start

### ISSUE THREAD

**Issue by sayduck-daniel** [rubyide/vscode-ruby#549]
When I reload my vscode and go into a ruby file I get this in Ruby Language Server console:

```log
[Info  - 12:39:04 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/tree-sitter-ruby.wasm
/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function i(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}},function(t,e,n){"use strict";n.d(e,"a",function(){return l});var r=n(0),i=n(25),o=n(57),s=n(5),u=n(41),a=n(14),c=n(35),l=function(t){function e(n,r,i){var s=t.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof e?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new f(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new f(s,n,r,i)}return s}return r.a(e,t),e.prototype[u.a]=function(){ret

Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130279
    at e.t (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130899)
    at new e (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:132561)
    at Function.t.parse (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:131794)
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285178
    at Object.keys.map.r (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285225)
    at Array.map (<anonymous>)
    at e.o.from.pipe.s.mergeMap [as project] (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285012)
    at e._tryNext (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30596)
    at e._next (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30498)
[Info  - 12:39:05 PM] Connection to server got closed. Server will restart.
[Info  - 12:39:05 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/tree-sitter-ruby.wasm
/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function i(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}},function(t,e,n){"use strict";n.d(e,"a",function(){return l});var r=n(0),i=n(25),o=n(57),s=n(5),u=n(41),a=n(14),c=n(35),l=function(t){function e(n,r,i){var s=t.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof e?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new f(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new f(s,n,r,i)}return s}return r.a(e,t),e.prototype[u.a]=function(){ret

Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130279
    at e.t (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130899)
    at new e (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:132561)
    at Function.t.parse (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:131794)
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285178
    at Object.keys.map.r (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285225)
    at Array.map (<anonymous>)
    at e.o.from.pipe.s.mergeMap [as project] (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285012)
    at e._tryNext (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30596)
    at e._next (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30498)
[Info  - 12:39:05 PM] Connection to server got closed. Server will restart.
[Info  - 12:39:06 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/tree-sitter-ruby.wasm
/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function i(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}},function(t,e,n){"use strict";n.d(e,"a",function(){return l});var r=n(0),i=n(25),o=n(57),s=n(5),u=n(41),a=n(14),c=n(35),l=function(t){function e(n,r,i){var s=t.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof e?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new f(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new f(s,n,r,i)}return s}return r.a(e,t),e.prototype[u.a]=function(){ret

Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130279
    at e.t (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130899)
    at new e (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:132561)
    at Function.t.parse (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:131794)
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285178
    at Object.keys.map.r (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285225)
    at Array.map (<anonymous>)
    at e.o.from.pipe.s.mergeMap [as project] (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285012)
    at e._tryNext (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30596)
    at e._next (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30498)
[Info  - 12:39:06 PM] Connection to server got closed. Server will restart.
[Info  - 12:39:06 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/tree-sitter-ruby.wasm
/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function i(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}},function(t,e,n){"use strict";n.d(e,"a",function(){return l});var r=n(0),i=n(25),o=n(57),s=n(5),u=n(41),a=n(14),c=n(35),l=function(t){function e(n,r,i){var s=t.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof e?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new f(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new f(s,n,r,i)}return s}return r.a(e,t),e.prototype[u.a]=function(){ret

Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130279
    at e.t (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130899)
    at new e (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:132561)
    at Function.t.parse (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:131794)
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285178
    at Object.keys.map.r (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285225)
    at Array.map (<anonymous>)
    at e.o.from.pipe.s.mergeMap [as project] (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285012)
    at e._tryNext (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30596)
    at e._next (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30498)
[Info  - 12:39:06 PM] Connection to server got closed. Server will restart.
[Info  - 12:39:07 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/tree-sitter-ruby.wasm
/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function i(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}},function(t,e,n){"use strict";n.d(e,"a",function(){return l});var r=n(0),i=n(25),o=n(57),s=n(5),u=n(41),a=n(14),c=n(35),l=function(t){function e(n,r,i){var s=t.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof e?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new f(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new f(s,n,r,i)}return s}return r.a(e,t),e.prototype[u.a]=function(){ret

Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130279
    at e.t (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:130899)
    at new e (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:132561)
    at Function.t.parse (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:131794)
    at /Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285178
    at Object.keys.map.r (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285225)
    at Array.map (<anonymous>)
    at e.o.from.pipe.s.mergeMap [as project] (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:285012)
    at e._tryNext (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30596)
    at e._next (/Users/daniel/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/index.js:16:30498)
[Error - 12:39:07 PM] Connection to server got closed. Server will not be restarted.
```

I have a ./vscode/settings.json in my project
```json
  "ruby.useLanguageServer": true,
  "ruby.lint": {
    "rubocop": {
      "forceExclusion": true,
      "rails": true,
      "lint": true
    },
    "reek": false
  },
```

Everything was working fine 2 days ago, I updated the extension and stuff stopped working

**Comment by sayduck-daniel** [comment]
I don't know if it can help but I have this `.rubocop.yml` in my project root folder:

```yml
---
require:
  - rubocop-rails
  - rubocop-performance

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Whitelist:
    - touch

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "config/routes.rb"

AllCops:
  Exclude:
    - "db/**/*"
    - "node_modules/**/*"
    - "spec/services/import_delivery_document_service_spec.rb"
    - "app/services/import_delivery_document_service.rb"

# [NOTE] Bugged at the moment

Rails/ActiveRecordOverride:
  Enabled: false
```

**Comment by wingrunr21** [comment]
Dup of #533

**Comment by baelter** [comment]
FYI this only happens to me while debugging
