### ISSUE TITLE
Language server crash with schema error

### ISSUE THREAD

**Issue by baelter** [rubyide/vscode-ruby#567]
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: 2.6.5
- Ruby version manager (if any): rbenv
- VS Code version: 1.40.2
- Operating System: Macos Catalina
- Using language server? (eg `useLanguageServer` is true?) yes

### Expected behavior
No crash

### Actual behavior
Crash
 
```
Loading Ruby tree-sitter syntax from /Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/tree-sitter-ruby.wasm
/Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function i(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}},function(t,e,n){"use strict";n.d(e,"a",function(){return l});var r=n(0),i=n(26),o=n(57),s=n(5),u=n(42),a=n(14),c=n(37),l=function(t){function e(n,r,i){var s=t.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof e?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new f(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new f(s,n,r,i)}return s}return r.a(e,t),e.prototype[u.a]=function(){ret

Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at /Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:62004
    at e.t (/Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:62624)
    at new e (/Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:64286)
    at Function.t.parse (/Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:63519)
    at /Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293468
    at /Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293515
    at Array.map (<anonymous>)
    at e.project (/Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293302)
    at e._tryNext (/Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:30637)
    at e._next (/Users/anders/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:30539)
[Error - 1:49:06 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by wingrunr21** [comment]
Dup of #549

**Comment by baelter** [comment]
FYI this only happens to me while debugging. With this config: 
```
 {
      "name": "Debug Local File",
      "type": "Ruby",
      "request": "launch",
      "program": "${file}"
    }
```

**Comment by baelter** [comment]
.. When the debugger steps into a gem, and therefore the is no rubocop.yml in the tree.

**Comment by baelter** [comment]
... putting a .rubocop.yml in the root of the tree did not solve it though...
