### ISSUE TITLE
Crash on go to definition

### ISSUE THREAD

**Issue by amerov** [rubyide/vscode-ruby#570]
### Your environment
- `vscode-ruby` version: 0.26.0 
- Ruby version: 2.5.5
- Ruby version manager (if any): chruby
- VS Code version: 1.40.2
- Operating System: 18.04.1-Ubuntu
- Using language server? (eg `useLanguageServer` is true?) Yes

### Expected behavior
Don't crash
### Actual behavior
Crash on go to definition
debug output:
```
Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at /home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:62004
    at e.t (/home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:62624)
    at new e (/home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:64286)
    at Function.t.parse (/home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:63519)
    at /home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293468
    at /home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293515
    at Array.map (<anonymous>)
    at e.project (/home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293302)
    at e._tryNext (/home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:30637)
    at e._next (/home/amerov/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:30539)
[Error - 4:22:26 PM] Connection to server got closed. Server will not be restarted.

```

**Comment by peret** [comment]
I also get this error when opening some Ruby files and also while debugging and stepping through the code. I couldn't really identify a pattern yet, though.
