### ISSUE TITLE
Bundler different behavior on terminal and language server

### ISSUE THREAD

**Issue by javidh** [rubyide/vscode-ruby#603]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.4.4
- Ruby version manager (if any): rbenv
- VS Code version: 1.44
- Operating System: macos Catalina 
- Using language server? yes

### Expected behavior
When I want to run linter on my ruby files, it won't work. 

### Actual behavior
The linter should've worked. The bundler install has already been done in the directory and the command `bundle exec rubocop -s  ... ` works in the terminal. 

The Ruby language server output is as follows 
```

Bundler::GemNotFound: Could not find activerecord-import-1.0.4 in any of the sources
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:87:in `block in materialize'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `map!'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `materialize'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/definition.rb:226:in `requested_specs'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:108:in `block in definition_method'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:20:in `setup'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-2.0.2/lib/bundler/setup.rb:20:in `<top (required)>'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/javidhosseini/.rbenv/versions/2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'

```

**Comment by javidh** [comment]
Turns out the problem was due to an iTerm script I ran. The script just launches a few tmuxinator instances and it messed up `GEM_HOME`. `unset GEM_HOME` fixed the problem.
