### ISSUE TITLE
Loads system Ruby instead of rbenv version on Catalina

### ISSUE THREAD

**Issue by dbaron-tc** [rubyide/vscode-ruby#671]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.7.2
- Ruby version manager (if any): rbenv 1.1.2 (installed via homebrew)
- VS Code version:
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
- Operating System: macOS Catalina 10.15.7
- Using language server? (eg `useLanguageServer` is true in your configuration?) Yes, ruby config in `settings.json`:
```
// PLUGIN: Ruby
    // Use built-in language server
    "ruby.useLanguageServer": true,
    // Time (ms) to wait after keypress before running enabled linters.
    "ruby.lintDebounceTime": 1500,
    //run non-lint commands with bundle exec
    "ruby.useBundler": true,
    // Set individual ruby linters to use (https://github.com/rubyide/vscode-ruby/blob/master/docs/linting.md)
    "ruby.lint": {
        // enable rubocop via bundler
        "rubocop": {
            // Prefix the `rubocop` command with `bundle exec`
            "useBundler": true,
        }
    },
    // Which system to use for formatting. Use `false` to disable or if another extension provides this feature.
    // "ruby.format": "standard",
    "ruby.format": "rubocop"
```
- Output of `gem env`:
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.4
  - RUBY VERSION: 2.7.2 (2020-10-01 patchlevel 137) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Users/dbaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /Users/dbaron/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/dbaron/.rbenv/versions/2.7.2/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/dbaron/.rbenv/versions/2.7.2/bin
  - SPEC CACHE DIRECTORY: /Users/dbaron/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/dbaron/.rbenv/versions/2.7.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /Users/dbaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
     - /Users/dbaron/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/dbaron/.rbenv/versions/2.7.2/bin
     - /usr/local/Cellar/rbenv/1.1.2/libexec
     - /Users/dbaron/.rbenv/shims
     - /Users/dbaron/.nvm/versions/node/v12.19.0/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
```

### Expected behavior

Language server should start and Ruby functionality should be available, for the Ruby version as configured via rbenv. For example if project root contains a file `.ruby-version` specifying Ruby version 2.7.2, then extension would use 2.7.2.

### Actual behavior

Language server fails to start. Dev tools console output shows (I added line breaks for legibility)
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': 
Could not find 'bundler' (2.1.4) required by your /Users/dbaron/path/to/my/project/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'	from /usr/bin/bundle:23:in `<main>'
```

However, the expected version of bundler is installed:
```
gem info bundler

*** LOCAL GEMS ***

bundler (2.1.4)
    Authors: André Arko, Samuel Giddins, Colby Swandale, Hiroshi
    Shibata, David Rodríguez, Grey Baker, Stephanie Morillo, Chris
    Morris, James Wen, Tim Moore, André Medeiros, Jessica Lynn Suttles,
    Terence Lee, Carl Lerche, Yehuda Katz
    Homepage: https://bundler.io
    License: MIT
    Installed at (default): /Users/dbaron/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0
```

It looks like the extension is attempting to load the system Ruby that comes with Catalina rather than the Ruby version as specified by rbenv.

Here is the system ruby:
```
ls -l /System/Library/Frameworks/Ruby.framework/Versions
total 0
drwxr-xr-x  6 root  wheel  192 28 Sep 06:50 2.6
lrwxr-xr-x  1 root  wheel    3  5 Dec  2019 Current -> 2.6
```

Whereas here is the Ruby version specified by rbenv:
```
rbenv versions
  system
  2.3.3
  2.6.6
* 2.7.2 (set by /Users/dbaron/path/to/my/project/.ruby-version)
```

I'm launching VS Code from terminal at project root (which contains `.ruby-version` file) using: 
```
code .
```

Have read the [language server doc](https://github.com/rubyide/vscode-ruby/blob/master/docs/language-server.md) but couldn't find if there's any additional config need to specify to make it work.

Does anyone know how to configure the ruby vscode extension to use the Ruby version from rbenv?

**Comment by dbaron-tc** [comment]
Adding this to `settings.json` seems to have solved it, was having similar issue with Solargraph:

```
"ruby.pathToBundler": "/Users/dbaron/.rbenv/shims/bundle",
"solargraph.bundlerPath": "/Users/dbaron/.rbenv/shims/bundle",
```
