### ISSUE TITLE
formatting is broken

### ISSUE THREAD

**Issue by joelcahalan** [rubyide/vscode-ruby#694]
### Your environment

- `vscode-ruby` version: 0.28.0
- Ruby version: 2.7.2
- Ruby version manager (if any): asdf
- VS Code version: 1.52.1
- Operating System: mac os catalina 10.15.7
- Using language server? (eg `useLanguageServer` is true in your configuration?) yes

### Expected behavior
auto formating to work
### Actual behavior
the following repeats over and over in the output console:
Format: executing bundle exec rubocop -s '/Users/joel/Source/railsapplication/app/...' -a...
undefined

when I execute the command in the terminal as suggested in the docs it works

**Comment by wingrunr21** [comment]
Can you please increase log verbosity (`ruby.languageServer.logLevel` config key) and verify the environment it is executing against looks correct?

**Comment by joelcahalan** [comment]
I tried both `"ruby.languageServer.loglevel": "debug"` and `"ruby.languageServer.loglevel": "trace"` but this did not change the output at all.

**Comment by wingrunr21** [comment]
`loglevel` is not `logLevel`

**Comment by joelcahalan** [comment]
oops, my autocomplete did that. Here is the trace:
```
    at t._subscribe (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:185576)
    at t._trySubscribe (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5410)
    at t.subscribe (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5196)
    at t.call (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:79920)
    at t.subscribe (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5067)
    at t.call (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:99662)
    at t.subscribe (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5067)
    at t.call (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:97901)
    at t.subscribe (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5067)
    at t.call (/Users/joel/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:83958)
undefined
```

**Comment by joelcahalan** [comment]
The env list home, lang and path keys with values that seem ok? Does the path require something special?

**Comment by joelcahalan** [comment]
I use asdf to manage ruby versions and I did a reshim to see if that would help, but still getting the same output.

**Comment by joelcahalan** [comment]
I would really like for auto formatting to work. Does anyone have a suggestion on how to fix this?

**Comment by ccutrer** [comment]
I'm seeing the same issue. I can confirm that the command is executing correctly, by adding some output to $stderr in the Gemfile itself, but still get `undefined` in the vscode console:


```
Format: executing bundle exec rubocop -s '/Users/cody/src/canvas-lms/lib/data_fixup/backfill_nulls.rb' -a...
Trace: spawning process: bundle exec,rubocop,-s,'/Users/cody/src/canvas-lms/lib/data_fixup/backfill_nulls.rb',-a, {"env":{"GEM_HOME":"/Users/cody/.gem/ruby/2.7.2","GEM_PATH":"/Users/cody/.gem/ruby/2.7.2:/Users/cody/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0","GEM_ROOT":"/Users/cody/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0","HOME":"/Users/cody","PATH":"/Users/cody/.gem/ruby/2.7.2/bin:/Users/cody/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/bin:/Users/cody/.rubies/ruby-2.7.2/bin:/Users/cody/.nvm/versions/node/v14.15.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin","RUBYOPT":"","RUBY_ENGINE":"ruby","RUBY_ROOT":"/Users/cody/.rubies/ruby-2.7.2","RUBY_VERSION":"2.7.2"},"cwd":"/Users/cody/src/canvas-lms/lib/data_fixup"}
    at t._subscribe (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:185576)
    at t._trySubscribe (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5410)
    at t.subscribe (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5196)
    at t.call (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:79920)
    at t.subscribe (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5067)
    at t.call (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:99662)
    at t.subscribe (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5067)
    at t.call (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:97901)
    at t.subscribe (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:5067)
    at t.call (/Users/cody/.vscode/extensions/rebornix.ruby-0.28.1/dist/server/index.js:16:83958)
hello from the gemfile!

undefined
```
