### ISSUE TITLE
Initializing language server fails: TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by avdv** [rubyide/vscode-ruby#724]
### Your environment

- `vscode-ruby` version: 0.27.0 (edited: *was*: 0.28.0)
- Ruby version: 2.6.6
- Ruby version manager (if any):
- VS Code version: vscodium 1.51.1
- Operating System: linux
- Using language server? (eg `useLanguageServer` is true in your configuration?) yes.

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-12T00:31:42.540Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.7-zen1
```

### Expected behavior

Language server would be working.

### Actual behavior

```
Initializing Ruby language server...
TypeError: Cannot read property 'apply' of undefined
    at t.<computed> (/home/claudio/.vscode-oss/extensions/rebornix.ruby-0.28.0/dist/server/index.js:16:235184)
    at <anonymous>:wasm-function[20]:0x908
    at <anonymous>:wasm-function[19]:0x4a8
    at <anonymous>:wasm-function[80]:0x15c68
    at <anonymous>:wasm-function[129]:0x25fcc
    at ts_parser_parse_wasm (<anonymous>:wasm-function[248]:0x2d59c)
    at Object.s._ts_parser_parse_wasm (/home/claudio/.vscode-oss/extensions/rebornix.ruby-0.28.0/dist/server/index.js:16:246177)
    at he.parse (/home/claudio/.vscode-oss/extensions/rebornix.ruby-0.28.0/dist/server/index.js:16:261381)
    at Object.createTree (/home/claudio/.vscode-oss/extensions/rebornix.ruby-0.28.0/dist/server/index.js:16:176060)
    at e.project (/home/claudio/.vscode-oss/extensions/rebornix.ruby-0.28.0/dist/server/index.js:16:176536)
[Error - 10:07:57 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 10:07:58 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 10:08:01 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 10:08:01 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
[Error - 10:08:01 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 10:13:06 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'foldingRanges' of undefined
  Code: -32603 
[Error - 10:13:06 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'documentSymbols' of undefined
  Code: -32603 
...
```

**Comment by jaimem88** [comment]
FWIW downgrading to `v0.27.0` makes this issue go away 🤷‍♂️

**Comment by jaimem88** [comment]
Actually upgrading to `v0.28.1` so this seems like a duplicate of https://github.com/rubyide/vscode-ruby/issues/693#issuecomment-757054972

**Comment by avdv** [comment]
Sorry, how do you upgrade to 0.28.1? Latest version in the marketplace is 0.28.0... ?

**Comment by avdv** [comment]
Update: I have upgraded rebornix.ruby to version 0.28.1 and it is working now!

*Note*: I just realized that I am still using version 0.27.0 of vscode-ruby (I am using OpenVSX registry since I am using VSCodium and the extensions available there is 0.27.0 for vscode-ruby and 0.28.0 for rebornix.ruby).

**Comment by avdv** [comment]
Closing, as the issue is resolved for me.

**Comment by jaimem88** [comment]
FTR if you are using codium you need to [enable the marketplace extensions](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace)
