### ISSUE TITLE
Debugger does not work unless rake gem is present

### ISSUE THREAD

**Issue by davidpcaldwell** [rubyide/vscode-ruby#733]
### Your environment

- `vscode-ruby` version: just installed 0.28.1
- Ruby version: 2.6.5 (Homebrew)
- Ruby version manager (if any): Homebrew
- VS Code version: 1.55.2
- Operating System: macOS Big Sur
- Using language server? (eg `useLanguageServer` is true in your configuration?): false

### Expected behavior
Debugger runs if `ruby-debug-ide` and `debase` gems are available, according to [the documentation](https://github.com/rubyide/vscode-ruby/blob/master/docs/debugger.md)

### Actual behavior
Does not run -- complains `rake` is missing:
```
local/homebrew/Cellar/ruby@2.6/2.6.7/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'rake' (>= 0.8.1) among 39 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=local/homebrew/lib/ruby/gems/2.6.0', execute `gem env` for more information
	from local/homebrew/Cellar/ruby@2.6/2.6.7/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
	from local/homebrew/Cellar/ruby@2.6/2.6.7/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from local/homebrew/Cellar/ruby@2.6/2.6.7/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from local/homebrew/Cellar/ruby@2.6/2.6.7/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	from local/homebrew/Cellar/ruby@2.6/2.6.7/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	from local/homebrew/Cellar/ruby@2.6/2.6.7/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	from local/homebrew/Cellar/ruby@2.6/2.6.7/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	from local/homebrew/lib/ruby/gems/2.6.0/bin/rdebug-ide:23:in `<main>'

Installing `rake` fixes the problem.

A few years back I was able to create a similar setup without `rake`. Perhaps this dependency has been added and the documentation is out of date?

**Comment by davidpcaldwell** [comment]
As best I know, this issue is still valid.
