### ISSUE TITLE
Unable to install gem ruby-debug-ide

### ISSUE THREAD

**Issue by c0m3tx** [rubyide/vscode-ruby#75]
### Your environment

- `vscode-ruby` version: 0.8
- Ruby version: 2.3.0
- VS Code version: 1.5.3
- Operating System: Arch Linux
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

I'm trying to install ruby-debug-ide but it does not work:

    ~ gem install ruby-debug-ide -v 0.4.32
    Building native extensions.  This could take a while...
    ERROR:  Error installing ruby-debug-ide:
	ERROR: Failed to build gem native extension.

    current directory: /home/c0m3tx/.gem/ruby/2.3.0/gems/ruby-debug-ide-0.4.32/ext
    /usr/bin/ruby mkrf_conf.rb
    Installing base gem
    You don't have write permissions for the /usr/lib/ruby/gems/2.3.0 directory.
    /usr/lib/ruby/2.3.0/rubygems/installer.rb:685:in `verify_gem_home'
       /usr/lib/ruby/2.3.0/rubygems/installer.rb:805:in `pre_install_checks'
       /usr/lib/ruby/2.3.0/rubygems/installer.rb:272:in `install'
       /usr/lib/ruby/2.3.0/rubygems/request_set.rb:167:in `block in install'
       /usr/lib/ruby/2.3.0/rubygems/request_set.rb:151:in `each'
       /usr/lib/ruby/2.3.0/rubygems/request_set.rb:151:in `install'
       /usr/lib/ruby/2.3.0/rubygems/dependency_installer.rb:405:in `install'
       mkrf_conf.rb:35:in `rescue in <main>'
       mkrf_conf.rb:28:in `<main>'

I tried installing it as root but then I can't access the binary (which is located in /root/.gem/ruby/2.3.0/bin).
I tried putting the gem in my Gemfile but does not work (same error)

Why does it try to write in /usr/lib? Any way to bypass this behavior?
Thanks in advance

**Comment by c0m3tx** [comment]
I'll post the issue in the ruby-debug-ide project, since it belongs there more than here.

Sorry for bothering.
