### ISSUE TITLE
Extension fails to start with TypeError

### ISSUE THREAD

**Issue by hybridAries** [rubyide/vscode-ruby#776]
### Your environment

- `vscode-ruby` version: 0.28.1
- Ruby version: 3.0.2
- Ruby version manager (if any): asdf
- VS Code version: 1.61.2
- Operating System: Linux 5.14.15 kernel x86_64
- Using language server? (eg `useLanguageServer` is true in your configuration?) No

### Expected behavior
For linting and formatting to work in a new rails project with standardrb.

### Actual behavior
The extension fails to start when opening a Ruby file in a new Rails project. The extension host log window gives the following output:

```log
[2021-11-03 13:23:50.173] [exthost] [error] TypeError: u[t] is not a constructor
	at c._runLinters (/home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:9:100387)
	at c.run (/home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:9:98899)
	at t.LintCollection.run (/home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:9:97999)
	at r (/home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:9:94677)
	at Array.forEach (<anonymous>)
	at Object.t.registerLinters (/home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:9:95207)
	at /home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:1:78681
	at Generator.next (<anonymous>)
	at /home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:1:77907
	at new Promise (<anonymous>)
	at r (/home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:1:77655)
	at t.activate (/home/aries/.vscode/extensions/rebornix.ruby-0.28.1/dist/client/ruby.js:1:78420)
	at Function._callActivateOptional (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:15028)
	at Function._callActivate (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:14704)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12907
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 1)
```

My ruby VSCode config:

```json
  "ruby.codeCompletion": false,
  "ruby.useLanguageServer": false,
  "ruby.intellisense": false,
  "ruby.useBundler": true,
  "ruby.format": "standard",
  "ruby.lint": {
    "standard": true
  },
  "[ruby]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.defaultFormatter": "rebornix.ruby"
  },
```

My Gemfile is a standard new Rails 6.1.4.1 project with the `standard` gem added to the Gemfile.

**Comment by lucasprag** [comment]
I'm also having the same problem.

My settings are just:
```json
"ruby.lint": {
  "standard": true
},
```

However, if I use rubocop, it works and I can see linting warnings on my code.

```json
"ruby.lint": {
  "rubocop": true
},
```

I tried removing all ruby related extensions and others as well.

**Comment by lucasprag** [comment]
Hey @wingrunr21 , is there anything I can do to help with this issue? 🙏 

I tried building the project locally following the instructions on [developing.md#getting-started](https://github.com/rubyide/vscode-ruby/blob/main/docs/developing.md#getting-started), but I get this error:

![wasm](https://user-images.githubusercontent.com/2293178/146615530-149ab809-10fd-4c26-acdf-0bbafde06b37.png)

It sounds like [this dependency might be wrong](https://github.com/rubyide/vscode-ruby/blob/330dcd2af212a336eba791ac0bd185f1c78042d7/packages/language-server-ruby/package.json#L18). I think that's the case because I can't find [a package called "web-tree-sitter-ruby" on npm](https://www.npmjs.com/search?q=web-tree-sitter-ruby). However I'm able to find one called [tree-sitter-ruby](https://www.npmjs.com/package/tree-sitter-ruby) and it even matches the most recent version on your `package.json`, which is `0.19.0`, but I'm not sure exactly what is happening 🤔

**Comment by wingrunr21** [comment]
`web-tree-sitter-ruby` is in the `packages` directory.  It isn't wrong 😉
