### ISSUE TITLE
yarn build fails: ENOENT: no such file or directory, copyfile 'node_modules/web-tree-sitter/tree-sitter.wasm' -> 'dist/tree-sitter.wasm'

### ISSUE THREAD

**Issue by technicalpickles** [rubyide/vscode-ruby#792]
### Your environment

- `vscode-ruby` version: main branch
- Ruby version: n/a
- Ruby version manager (if any): n/a
- VS Code version: n/a
- Operating System: macOS Monterey
- Using language server? (eg `useLanguageServer` is true in your configuration?): n/a

### Expected behavior

Based on docs/development, I expect `yarn build` to succeed

### Actual behavior

```
$ yarn build

yarn run v1.22.17
$ lerna run build
lerna notice cli v3.22.1
lerna info Executing command in 4 packages: "yarn run build"
lerna info run Ran npm script 'build' in 'vscode-ruby-debugger' in 0.5s:
$ yarn compile --minify
$ esbuild ./src/main.ts --bundle --outfile=dist/main.js --external:vscode --format=cjs --platform=node --minify
lerna info run Ran npm script 'build' in 'web-tree-sitter-ruby' in 23.2s:
$ tree-sitter build-wasm --docker ../../node_modules/tree-sitter-ruby
lerna ERR! yarn run build exited 1 in 'language-server-ruby'
lerna ERR! yarn run build stdout:
$ NODE_ENV=production node esbuild.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
✘ [ERROR] [plugin treeSitterWasm] ENOENT: no such file or directory, copyfile '/Users/josh.nichols/workspace/vscode-ruby/node_modules/web-tree-sitter/tree-sitter.wasm' -> 'dist/tree-sitter.wasm'

    /Users/josh.nichols/workspace/vscode-ruby/packages/language-server-ruby/esbuild.js:15:9:
      15 │       fs.copyFileSync(wasmPath, path.join(outDir, path.basename(wa...
         ╵          ^

    at Object.copyFileSync (node:fs:2800:3)
    at /Users/josh.nichols/workspace/vscode-ruby/packages/language-server-ruby/esbuild.js:15:10
    at Array.forEach (<anonymous>)
    at setup (/Users/josh.nichols/workspace/vscode-ruby/packages/language-server-ruby/esbuild.js:14:15)
    at handlePlugins (/Users/josh.nichols/workspace/vscode-ruby/node_modules/esbuild/lib/main.js:814:23)
    at Object.buildOrServe (/Users/josh.nichols/workspace/vscode-ruby/node_modules/esbuild/lib/main.js:1108:7)
    at /Users/josh.nichols/workspace/vscode-ruby/node_modules/esbuild/lib/main.js:1961:17
    at new Promise (<anonymous>)
    at Object.build (/Users/josh.nichols/workspace/vscode-ruby/node_modules/esbuild/lib/main.js:1960:14)
    at Object.build (/Users/josh.nichols/workspace/vscode-ruby/node_modules/esbuild/lib/main.js:1814:51)

error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'language-server-ruby'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: node /opt/homebrew/Cellar/yvm/4.1.4/versions/v1.22.17/bin/yarn.js build
```

**Comment by hiichan** [comment]
@wingrunr21 

Hi!

I got the same error yet.
How can i fix it?

operation:

```
git clone https://github.com/rubyide/vscode-ruby
cd vscode-ruby
yarn install
yarn watch
```
