### ISSUE TITLE
vscode-ruby 0.10.0 does not load

### ISSUE THREAD

**Issue by artem-sidorenko** [rubyide/vscode-ruby#83]
### Your environment

- `vscode-ruby` version: 0.10.0
- Ruby version: 2.3.1
- VS Code version: 1.6.0
- Operating System: Linux Mint 18
- Hardware (optional): 

### Expected behavior

Extension should be loaded and work

### Actual behavior

Extension does not work. In the vscode log I see following:

```
threadService.ts:222[Extension Host] Activating extension `rebornix.Ruby` failed:  Cannot find module './lint/LintCollection'(anonymous function) @ threadService.ts:222
threadService.ts:222[Extension Host] Here is the error stack:  Error: Cannot find module './lint/LintCollection'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.N.n._load (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:19970)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/artem/.vscode/extensions/rebornix.Ruby-0.10.0/ruby.js:8:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Steps to reproduce the problem
 - Install vscode
 - install ruby extension
 - open development log of vscode
 - reload vscode

**Comment by HookyQR** [comment]
My fault. Waiting for a patch to be published. See #81 for a manual fix in the meantime.
