### ISSUE TITLE
Rubocop linting

### ISSUE THREAD

**Issue by ahmetabdi** [rubyide/vscode-ruby#84]
Linting has stopped working for me in version `0.10.0` my settings.json and setup are unchanged.

```
"ruby.lint": {
  "reek": false,
  "rubocop": true,
  "ruby": true,
  "fasterer": false,
  "debride": false,
  "ruby-lint": false
}
```
These are the errors I get in the console not sure if they are related or not.

```
threadService.ts:222 [Extension Host] Uncaught Exception:  Error: write EPIPE(anonymous function) @ threadService.ts:222emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
threadService.ts:222 [Extension Host] Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)(anonymous function) @ threadService.ts:222emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
shell.ts:441 write EPIPE: Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)
```

**Comment by HookyQR** [comment]
@ahmetabdi, what OS are you on? If you're not on Mac OS you may be experience the problem I caused with the last release. See #81 for a manual fix.

**Comment by ahmetabdi** [comment]
I am on Mac Sierra
