### ISSUE TITLE
Uncaught exception while launching rails server in debug view

### ISSUE THREAD

**Issue by icnagy** [rubyide/vscode-ruby#90]
### Your environment

- `vscode-ruby` version: 0.10.3
- Ruby version: 2.3.1
- VS Code version: 1.7.1
- Operating System: macOS Sierra
- Hardware (optional): 

I am getting an error while trying to start the rails server from the debug view. 

Here's the relevant part of `launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
...
    {
      "name": "Rails server",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rails",
      "args": [
        "server"
      ]
     }
...
  ]
}

```
### Expected behavior

The rails server to start.

### Actual behavior

```
Uncaught exception: invalid byte sequence in US-ASCII
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/yaml_serializer.rb:55:in `split'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/yaml_serializer.rb:55:in `load'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:287:in `block in load_config'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:283:in `load_config'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:43:in `initialize'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:209:in `new'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:209:in `settings'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:438:in `configure_gem_path'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:433:in `configure_gem_home_and_path'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:62:in `configure'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:126:in `definition'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:93:in `setup'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
  /Users/username/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
  /Users/username/work/sso/bin/rake:15:in `<top (required)>'
  /Users/username/.rbenv/versions/2.3.1/bin/rdebug-ide:22:in `load'
  /Users/username/.rbenv/versions/2.3.1/bin/rdebug-ide:22:in `<main>'
/Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/yaml_serializer.rb:55:in `split': invalid byte sequence in US-ASCII (ArgumentError)
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/yaml_serializer.rb:55:in `load'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:287:in `block in load_config'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:105:in `filesystem_access'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:283:in `load_config'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/settings.rb:43:in `initialize'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:209:in `new'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:209:in `settings'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:438:in `configure_gem_path'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:433:in `configure_gem_home_and_path'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:62:in `configure'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:126:in `definition'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.rb:93:in `setup'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/setup.rb:20:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
  from /Users/username/work/sso/bin/rake:15:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_load'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_program'
  from /Users/username/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:130:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.3.1/bin/rdebug-ide:22:in `load'
  from /Users/username/.rbenv/versions/2.3.1/bin/rdebug-ide:22:in `<main>'
```

### Steps to reproduce the problem

1. Open Visual Studio Code
2. Open a Rails project
3. Goto Debug view
4. Select `Rails server` from the dropdown
5. Start debugging

**Comment by HookyQR** [comment]
Ouch. `ruby-debug-ide` doesn't like UTF-8 by default, but it looks like the `yaml_serializer` is doing the actual complaining here. I'll take a look and see if there is anything we can do from the r-debug end. Does the server run correctly from the (same) command line?

**Comment by icnagy** [comment]
@HookyQR thank you! Yes, I have no trouble running rails from command line. Let me know if you need any more input!

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
